### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#100]
## Dashboard

- if no monthly tasks are completed then show the following text:

"Please first complete the outstanding monthly tasks." 

- show a button "Tasks" which will redirect the user to the oldest task month (e.g. Jan) that is not yet complete.

Otherwise 

### Header Text
- Show the following text.

"The figures for "COMPANY NAME" reflect the accounts from 01-01-2017 to DD-MM-2017."

- replace company name with the name of the company (e.g. Portacom software limited)

- Calculate the DD-MM-2017 value using the monthly tasks  of status COMPLETED that is most recent.  For example, if Jan Feb and March are all completed, then show 31-MAR-2017.

**Outstanding Monthly Tasks**

- If there are outstanding monthly tasks (e.g. APRIL, MAY, JUNE, JULY, AUG) then display the following text also 
"Please complete the outstanding tasks for April, May, June, July, Aug to bring the figures up to date.".  -
- Show a button "Tasks"  which will redirect the user to the oldest task month 

### Dashboard content

#102 and others

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/29487803-a88aa67c-84ff-11e7-8d3c-b85409e33839.png)
![image](https://user-images.githubusercontent.com/546027/29487808-b06ed796-84ff-11e7-96fc-1057fe329621.png)

**Comment by fergalddaly** [comment]
tested and working.
