### ISSUE TITLE
Transaction Reconciliation Updates -- Part 1

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#104]
# Reason for change
- Allow the system to offer suggested categories for transactions 
- thus greatly reduce the categorisation manual work,
- Make categorisation of transaction very simple rather than onerous.

# Objectives
- application will determine the correct category based on past categorisations, based on vat return values, based on invoice values.
- the user will simply need to confirm that the system chosen value is correct

# Changes to achieve the above

## Categorising a Transaction

Note: after you click on "Update Transactions" button,  the transactions are shown with dropdowns.  This section relates to this section of the app.

**fa-floppy-o**
- currently when the user selects an item from the drop down a rest call is made.  Do not make a rest call on selection of an item.  Instead display icon "fa-floppy-o" on the right of the drop down when a user makes a selection.  
- when the user initially clicks on "Update Transaction" no "fa-floppy-o" icons will be displayed. When the user selects a category on a transaction, then the icon appears on that transaction.  
- the user can click on the icon "fa-floppy-o" and this will save the category - the rest call will be made to the server.
- when icon is pressed and the rest call is made, the icon is no longer displayed on that transaction.  the reconcile button will then be displayed. 

### More
- More changes in this areas are documented in #105 and #106.

### Green Tick only in edit mode (finished)
- change it so that the green tick is shown when you click on the "Update Transactions" (as you then know immediately that this transaction is fully complete and no action is required on it.)
- change it so that the green tick is not shown when you are viewing the transactions (as opposed to updating them).  so in this case only the warnings will be shown.

**Comment by fergalddaly** [comment]
@Keroberos  - I completed task #105 and committed it.  This will need to be merged with this change (as there will be small clash).

Currently the prediction is selected on the drop down (by the code) 
which results in the transaction category being set on the server.

When you make the change above, this will work properly - the prediction is selected but not set on the server; the save icon appears next to the predicted category type.  The user will then simply simply need to click on the save icon to make the rest call to set the category on the server.

**Comment by Keroberos** [comment]
Hi! It seems that changes in the liquibase schema was missed. Could you please commit your changes from .\src\main\resources\config\liquibase\changelog\ ?

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/29249796-f8656a2e-8036-11e7-828f-a68f66fdee8e.png)

**Comment by fergalddaly** [comment]
tested and working perfectly.
