### ISSUE TITLE
Bank Transaction Categorisation - Part 2 -- Predictions

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#105]
## Change

- A bank statement for Jan is uploaded, and categorised.
- Then a bank statement for Feb.
- The user then clicks on "Update Transactions".
- The system will display the drop downs.
- Some of the category drop down will already have pre-selected values

Next part requires #104 to be done first 
- Some of the category drop down will already have pre-selected values and the save button will be -
 displayed for these pre-selected dropdown.
- For these, the user will only need to click on the save icon to confirm that the system has pre-selected the correct category for the transaction.

## Note on Implementation.

- use the details of the past transactions to predict the category
- support exclusion where a transaction desc can mean many things (e.,g. payment to REVENUE).

**Comment by Keroberos** [comment]
Hi! It seems that changes in the liquibase schema was missed. Could you please commit your changes from .\src\main\resources\config\liquibase\changelog\ ?

**Comment by fergalddaly** [comment]
Committed that.
