### ISSUE TITLE
Misc UI Updates

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#108]
**Tasks**
- "Complete Tasks" button  - hide if not clickable (no disabled)
- add in a card top panel with month so that the month can be easily identified.

**Nav bar**
- Add "Work" menu to Nav Bar with drop down for Timesheets and Invoices
- Show submenus on hover.
- Remove arrow from dropdown
- add "Money" menu and submenu for Expenses

**Timesheets**
- show icons in dropdowns.
- remove colour from icons representing days.
- add in a card top panel with month so that the month can be easily identified.

**Comment by fergalddaly** [comment]
@Keroberos - if you could take a few minutes to have a quick review of these changes. My level of knowledge of typescript/angular is not at your level.

**Comment by Keroberos** [comment]
good job, everything is looking fine

**Comment by fergalddaly** [comment]
Thanks, feel free to correct or provide feedback on any of my angular work.
I'm going to "copy" the patterns you have used.
