### ISSUE TITLE
Create Company, Contract(&Client&Agency), User Preferences Pages

### ISSUE THREAD

**Issue by Keroberos** [Keroberos/sam#18]

**Comment by fergalddaly** [comment]
First Page of setup data
I think the best option is to put an menu item for it on the user menu on the right.
This is not something that will be done too many times once the data has been correctly entered.

User Preferences
These might change from time to time but not so often - so again, this can be an item on the user menu on the very right,
Would be good to have an separate menu item for this page (User Preferences).
These preferences might grow over time.

**Comment by fergalddaly** [comment]
Tested. Working perfectly. Great!
Another task completed :+1: 

![image](https://user-images.githubusercontent.com/2511712/28695326-624cd026-7326-11e7-9d36-f48055afd29a.png)
