### ISSUE TITLE
Companies not displaying for the admin user

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#19]
When you log in as the admin user and go to Entities/Companies only the text Companies is displayed, but not actually the companies themselves.
I checked in the database and they do exist.
I checked the code but I couldn't figure out what was different with this entity and the other entities.
I think it might be to do with the roles but I am not sure.

Note: I'd be interested to learn what the issue actually was if you figure this out.

**Comment by Keroberos** [comment]
The reason was in security settings on the server side
![2](https://user-images.githubusercontent.com/546027/27768301-e6027ed2-5f0f-11e7-8ad3-ce81edeb777f.PNG)
