### ISSUE TITLE
Bank Statement Color 

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#32]
CHANGE TO display-bank-statement.component.html

Currently the if a bank statement is incomplete its tab is displayed in red.

Change to:
  - display incomplete statements where the month is not the current month in red.
  - if the statement is the current month then display as gray (btn-primary)

If complete leave as it is (in green).

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28036053-154a8966-65b7-11e7-8b18-5dcb552a47da.png)
