### ISSUE TITLE
Contract Updates - Status and Notice Period 

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#36]
### Contract Status Update

- add a new TimesheetEntryStatus - OUT_OF_CONTRACT (see for details on how this will be used #49)

### Status 

- add a new enum entity called ContractStatus

PAST, ACTIVE, FUTURE

**Set Value on Entity at Contract Creation Time**

- Each contract will have a status set to one of the above based on the contract start and end dates and the current time.  This field is not user inputted.

- show this field (status) on the contract table - colour code (gray for past, active in green and -warning for future).

**Nightly cron job**

- Retrieve contracts and update status if necessary (note: retrieve all contracts and and determine the status and then update calculated status != status on contract entity).

### Notice Period

- add a new field to a contract - noticePeriodDays 

- this field is optional.

- show this on the contract table.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/29001986-1f094f28-7a98-11e7-85fa-c5d4f26ff262.png)

**Comment by fergalddaly** [comment]
tested and working perfectly.
