### ISSUE TITLE
Timesheets

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#37]
Background:
The user will be asked to log his/her time each week.  On the Friday of each week.
This will be managed by tasks.  
At the end of a month the timesheet entries  will then be used to calculate the number of days that are worked in a month.

###################################
Note on timesheet status

     UP_TO_DATE --- all entries are filled in.. have a status... if the month is the current month then all entries up to today have a status.  null can exist for future entries.

     UPDATES_REQUIRED - some entries have status null   (entries have been created but not yet updated). 

     COMPLETE -- all entries have been updated with a status and no more entries are required for this month (no future entries to consider)

     SUBMITTED - user can change from COMPLETE to SUBMITTED when the user is happy that the details are all correct.

###################################
Note on initialization

- when a user is created, create a timesheet for each month of the year.
when creating a timesheet also create all entries for the month
Use NULL in the database for represent no details.  
SO the entry will exist but the TimesheetEntryStatus is set to NULL._
For each Sat and Sun set the status to NOT_WORKING_DAY.

###############################################

**Nav**
- Create a new button on the nav header called Timesheets
(which will navigate to the timesheets)

**Timesheet Dashboard.**

Create a tab for each month just like you did for the bank statements.
From the first month until the current month.

**COLOURS**
Colour code the months just like you did for bank statements.
 
UP_TO_DATE = gray/silver
MISSING_ENTRIES = red
COMPLETE = light green
SUBMITTED = green

When you click on the month tab then you see the month timesheet display

**MONTH TIMESHEET DISPLAY**

![image](https://user-images.githubusercontent.com/2511712/28094628-bb5a100e-6695-11e7-9443-79d34978694d.png)

**CONTROL ON TOP**
On top put in a facility to allow the user to change to previous month or next Month.
for Example:
<< Jan >>

**CALENDAR DISPLAY**
Put a calendar on the right hand side.  

For example:
![image](https://user-images.githubusercontent.com/2511712/28094789-a9b56fdc-6696-11e7-9dc6-2f336587d0c9.png)

Start with Monday on the left.  Finish with Sunday on right.

**MONTH TIMESHEET DETAILS**
On the left show information on the monthly timesheet:

For example:

month:  January
status:    UPDATES_REQUIRED 
number of updates required:   11  days

_Note: only show line details missing if status is UPDATES_REQUIRED_ 

total work days:   23
days worked:        15  (so far this month)  
days off:                5    (so far this month)

_Note:  show (so far this month) only if month=current& status!=COMPLETE&!=SUBMITTED._

**COLOURING THE DAYS ON THE CALENDAR**
If a day is in the past and no details are present for the day then this is shown in red.
(or some other style which will make it clear to the user that the user must enter details for the particular date).  
Any day with status NOT_WORKING_DAY is set to colour gray. 
If a day is in the future, then it is shown in light gray and can only be updated to DAY_OFF.

NON_WORKING_DAYS should not be changed to DAY_OFF. They should only be changed to FULL_DAY or HALF DAY.

The calendar should be shown on a week by week basis.

**PREVIOUS and NEXT MONTH DAYS**
Show the days with their associated status from the previous month (if the 1st day of month does not start on Monday) in a lighter shade.
Show the days from the next month (if the last day of month is not a Sunday) in a lighter shade.
To update a different month the user first needs to change to the other month and then perform the updates.  These "other month days" are disabled for updating.  They are colored quite light so the user does not pay any attention to them but can see them.

**UPDATE STATUS OF EACH DAY**
The calendar will clearly show the status of each day.  
Can be centered text but must be clear to the user that the day was a full day, half day or day off.

If the status is missing and is needed (in the past or current day, and not a sat or sun), then it is clearly visible as the color will show this - as described in the previous section.
Then the user needs to click on the day and specify if it is a full day, half day, or day off.

Once the user specifies the status, the change is saved (REST call) and the UI is immediately updated.  
The details for the month on the left are updated.
The status of the month may be updated.

**PLANNED LEAVE**
Allow the user to specify days off for future days.
The user cannot enter any other details for days in the future.
(i.e. you are not allowed to specify a FULL_DAY for a day next week).

**QUICK ENTRY DROP DOWN MENU**
On the right hand side, add a drop down menu for each week.
This should be discreet.  It will contain either one or two options.
See next section.

**QUICK ENTRY**
Add an option that allows the user to fill in the week as a standard working week (full days from MON-FRI).  When the current day is before FRI of the week,only fill out the entries from MON-<<current day>.  
Do not show this option for future weeks.

**QUICK ENTRY LEAVE**
Add an option that allows a user to specify that the complete week was taken off.  This option can be shown for future weeks as well as past weeks... all weeks. 

**BUTTON AT END**
Once the status of the monthly timesheet is a COMPLETE, 
a button (SUBMIT) then appears which allows the user to submit the timesheet.
The status of the timesheet changes to SUBMITTED if the timesheet is submitted.
Once the timesheet is submitted then button changes to RETRACT.
When the RETRACT button is pressed the status changes back to COMPLETE.

**UPDATES / READ ONLY and STATUS**
The use is free to make any changes to the data until the timesheet is SUBMITTED.
It is read only when submitted.
To change it the user has to retract it (click button).  
The timesheet status will then change back to COMPLETE and then user can update it.

**Comment by fergalddaly** [comment]
- saw calendar on heroku. look great. perhaps you can remove the the drop down arrow (by changing the css display to none). I think this would make the calendar clearer.

- days worked -- is the total number of full days worked in the month... so if the contractor works 2 half days that is the same as 1 full day .  THis will be used in the invoice.

**Comment by Keroberos** [comment]
Thank you! I have a question about statuses:
> NON_WORKING_DAYS should not be changed to DAY_OFF. They should only be changed to FULL_DAY or HALF_DAY

If NON_WORKING_DAYS changes to FULL_DAY, then we need to allow change it back to NON_WORKING_DAYS, but not to DAY_OFF
To keep this logic we need somehow to save NON_WORKING_DAYS.
The only way without adding additional fields is to add new TimesheetEntryStatuses statuses like NON_WORKING_FULL_DAY and NON_WORKING_HALF_DAY
Then statuses conversion table for days in the past will looks like this:

NULL->FULL_DAY 
NULL->HALF_DAY
NULL->DAY_OFF 
 
FULL_DAY->HALF_DAY
FULL_DAY->DAY_OFF

HALF_DAY->FULL_DAY 
HALF_DAY->DAY_OFF

DAY_OFF->FULL_DAY 
DAY_OFF->HALF_DAY

NON_WORKING_DAYS -> NON_WORKING_FULL_DAY
NON_WORKING_DAYS -> NON_WORKING_HALF_DAY

NON_WORKING_FULL_DAY->NON_WORKING_DAYS
NON_WORKING_FULL_DAY->NON_WORKING_HALF_DAY

NON_WORKING_HALF_DAY->NON_WORKING_DAYS
NON_WORKING_HALF_DAY->NON_WORKING_FULL_DAY

Another option is to provide a service that will check if original day status was  NON_WORKING_DAYS...
Or add additional property to the TimesheetEntryDTO

**Comment by fergalddaly** [comment]
The less complicated the better.
Let me have a look at it tonight and then i can have a think and we can then discuss what is the best way forward on this.

**Comment by fergalddaly** [comment]
I was thinking that perhaps we can easily make this change on the server side.
So, if  request to change a entry is made to day off then simply check to see if it is a sat or sunday. if it is a sat or sunday, then change it to non working day rather than day off.  

On the client ui. the user will select day off but the the UI will reset back to non- working day display rather than showing day off. 

That's perfect, as it is not really a day off as the contractor should is not expected to be working on that day.

Sound ok ?

**Comment by fergalddaly** [comment]
Perhaps this should return the new status rather then the entry id.

```

 @PutMapping("/monthly-timesheets/{id}/timesheetEntries/{timeEntryId}/status")
    @Timed
    public ResponseEntity<?> updateTimesheetEntryStatus(@PathVariable Long id, @PathVariable Long timeEntryId,
            @RequestBody String status) throws URISyntaxException {
        log.debug("REST request to update entry MonthlyTimesheet : {}", timeEntryId);

        TimesheetEntryStatus entryStatus = TimesheetEntryStatus.valueOf(status);
        TimesheetEntryStatus newStatus = monthlyTimesheetService.updateTimesheetEntryStatus(id, timeEntryId, entryStatus);

        return ResponseEntity.ok().headers(HeaderUtil.createEntityUpdateAlert(ENTITY_NAME, timeEntryId.toString()))
                .build();
    }

```

**Comment by Keroberos** [comment]
> Perhaps this should return the new status rather then the entry id.

Now it returns empty body and timeEntryId puts into logs. Sure, we can make it return new status

> I was thinking that perhaps we can easily make this change on the server side.
> So, if a request to change an entry to day off is made to the server then first check to see if the day is a sat or sunday and if it is a sat or sunday, then set the status to NON_WORKING_DAY rather than day off.

Sounds good

**Comment by Keroberos** [comment]
Lets continue work on Timesheets in the other tasks

**Comment by Keroberos** [comment]
One more thing about handling non-working days:
Total working days = Total days - non working days
But if we overwrite non working days on the client side this calculation does not work as expected

**Comment by fergalddaly** [comment]
I agree that this "Total working days" does not really make much sense.
I think we can simply remove it completely from the UI as it is simply confusing and is not providing any useful information.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28357562-2ae303b4-6c6c-11e7-97c3-ad627eee447c.png)

**Comment by fergalddaly** [comment]
An excellent job.  All controls work are perfectly.
We will make styling changes in the future but the focus has been on getting everything working and stored properly in the database and that is the case.
Great to have this sorted.  

Note 1: The booking of future time off will be useful for planning leave and financial planning.
Note 2:  Addtional requirements will be required - see #49  - but this is "phase 2" of timesheets.
