### ISSUE TITLE
Timesheet Entity

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#38]
/* ####################################################### */

enum TimesheetEntryStatus {
FULL_DAY,
 HALF_DAY,
 OFF_DAY
 NOT_WORKING_DAY
}

entity TimesheetEntry {
  id Long required, 
  status TimesheetEntryStatus
}

/* ####################################################### */
    
   enum TimesheetStatus
   {
     UP_TO_DATE,
     MISSING_ENTRIES,
     COMPLETE,      
     SUBMITTED
   }
 

entity MonthlyTimesheet {
  id Long required, 
  month Integer required min(1) max(12) required,
  year Integer required min(2017) max(2050) required,
  status TimesheetStatus required
}
    
   relationship OneToMany {
   MonthlyTimesheet {User(id) required} to User
   }
  

--- ManyToOne  - this is not working properly in JHipster.
--- a timesheet entry is associated with ONE monthly timesheet
--  one monthly timesheet has many timesheet entries (e.g. 31).

   relationship ManyToOne {
   MonthlyTimesheet ---> TimesheetEntry
   }

Note: if possible would you be able to make the update to support the ManyToOne  a separate commit to the other parts of this requirement, so that I can easily see the changes that we need to make to support this.  

  dto MonthlyTimesheet with mapstruct
  service MonthlyTimesheet with serviceClass

**Comment by Keroberos** [comment]
> relationship OneToMany {
>   MonthlyTimesheet {User(id) required} to User
>   }
Should be ManyToOne

> relationship ManyToOne {
>   MonthlyTimesheet ---> TimesheetEntry
>   }
Should be OneToMany

> ManyToOne - this is not working properly in JHipster.
OneToMany is not supported out of the box

**Comment by Keroberos** [comment]
Separate commit to fix OneToMany:
https://github.com/Keroberos/sam/commit/cabe17b91bce7e970fd26433190440cb5c553fbf
