### ISSUE TITLE
SAM-39 - VAT Button and Vat colour.

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#40]
Updates for SAM-39 BRANCH.

**On UI**
Add a new column on the vat return table.
Each row has a button called action with a drop down

If the status is CREATED then 
the button should offer an option 
calculate and when choosen it calls
call PUT /api/vat-returns/{id}/calculate

If the status is CALCULATED then the drop down will also (see above) have the following option:
RECORD ROS PAYMENT
When this is choose then allow the user to enter the ROS payment number and ros payment date and when that is done, then a REST call is made to the server to update these details.
(The rest call needs to be added to the VatReturn resource. The service is already updated).

==============================================================

COLORS

If the due date is in the past and the status is CREATED then show the vat return in light red.
If the vat returns due date is in the past and the status is CALCULATED then set to orange
If the vat returns due date is in the past and the status is CALCULATED but ROS payment details have been added then show it in very light green.
If the vat return status is green then show it in green.

Note - I think it would be too much to show all the row in different colours so only add the color to the status column.

**Comment by fergalddaly** [comment]
Note once the above is done

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28189506-7f2ab560-6826-11e7-9681-07f45154252a.png)
