### ISSUE TITLE
Bank Account of other user being shown

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#41]
If you log in as a user and view your bank account transactions,
and log out and then log in as a different user, the first user's bank account transactions are shown.

**Comment by Keroberos** [comment]
Partialy should be fixed here: https://github.com/Keroberos/sam/commit/e057398e30149289f82b94fe3f9386bffeae0d4c by clearing SessionStorageService when logout, but still need to implement restrictions on the server side for user to see only his entities

**Comment by fergalddaly** [comment]
That's perfect.  That's the issue resolved.

I understand that we will need to do a complete review to ensure that a user is only reading and updating data that is owned by the user itself.  While there is nothing stopping a user changing the URL and guessing an id this is fine for now.  We can do all of this when we are happy that we are ready to go live.
