### ISSUE TITLE
Tasks Client UI

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#43]
See #42 

# Angular UI development work

1.   Create a **tasks button** on the top nav header.
When the user clicks on the task button the application changes to the tasks page.

1.  Create a **tasks page** which shows **monthly tabs from Jan to Dec**.  
(in the same way as the Bank Accounts Statements have been presented)
show the status in the same way.

1.  Each month tabs shows MonthlyTasks for the month the month tab that is selected.

1.  Colour each tab as follows:

NOT_YET_DUE - silver
INCOMPLETE - red
COMPLETE - green

1.   Show tasks sorted by order

1.  Show the following fields - type, status, dueDate, comment

1.  Color code the status as follows:

NOT_YET_DUE - gray
HAS_PREREQUISTE_TASKS - silver
TODO - red 
COMPLETED - green

1.  Add in a button, COMPLETE TASK.  If the status of the task is not_yet_due or has_prerequiste_tasks then disable the button.    If the status of the task is TODO then the button is enabled.  If the status of the task is COMPLETED, then don't show the button. 

1.  When the user clicks on the COMPLETE TASK button the App will change to the appropriate area of the app - e.g. if the task is an TIMESHEET tasks then the app will change to the TIMESHEET module and show the appropriate month.  If the task is an INVOICE then the app will change to the INVOICE module.  If the task is EXPENSE then goto Expenses.  If the task is BANK_ACCOUNT_UPLOAD or BANK_ACCOUNT_RECONCILIATION then go to the BankAccout module and to the appropriate month.
For VAT go to VAT module.

Note:  There is no way for the user to create or update tasks on the UI. These are created by the application on the server side and will be updated as the user actually performs the tasks (e.g. changes the status of the monthly timesheet to COMPLETE).

**Comment by fergalddaly** [comment]
I have committed d06d4d0d3d027b2910ff099b3e844c484382002b.
It might be helpful to this task to merge that to the branch.

**Comment by fergalddaly** [comment]
I updated the task by adding one extra point (disabled button).

**Comment by fergalddaly** [comment]
When working on the server side functionality of tasks, I encountered an issue.
I tried to create two tasks for the same bank statement but because of the one-to-one relationship between tasks and bank statements this was not possible.
I wanted to create a task for upload and a task for reconcilation.
Currently this is not supported.
So I simply created a task for reconciliation.

I can create a new issue to change this.
So a task can be associated with 1 bank statement.
But a bank statement can be associated with many tasks.

This might be useful for the other associations too... as it will be nice to break tasks down to different steps - but at the moment there is no requirement for this.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28501101-0d5bb5f4-6fd5-11e7-9809-7128a5bc5c63.png)

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28501283-06fbace2-6fd9-11e7-8867-e5cac0144a83.png)
Working fine in Heroku. But there are many synchronus operations on the server while creating a new User - free heroku dyno can't finish them all until REST register call timeout.

So you can get an error on client side during registration, but you will be able to login.

**Comment by fergalddaly** [comment]
Cheers.   I test with my local copy.
I noticed that the heroku server can run slowly sometimes.

I pulled that code to branch #44. 
Working great.
Closing this now.

Great to have this done as we can now drive the requirements from the tasks.
