### ISSUE TITLE
Invoice Status Update

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#46]
# Entity Changes
1. Create an association between the invoice and the monthly timesheet
1. When the invoices is being created, set the monthly timesheet on the invoice.

# Status
Add in a new status for invoices - ISSUED.

## Client UI
Issue Invoice Change
1. Add an "Issue Invoice" button on the invoice table to allow an invoice that is totalled to be issued.
1. Only show this button when the status is TOTALLED.
1. When the user clicks on the button make a REST call to the server to issue the invoice.
1. Create a method on the server to issue the invoice. For now it only changes the status from totalled to issued.  In the future, we will change this to actually send an invoice by mail as well.
Also update the issue date.

**Other changes**
1. Change the month numbers to Months (Jan, Feb, etc)
1. Remove the cols vat rate, vat amount from Client UI. 

1. Remove the ability to input days on invoices 
(note: this may be needed at some point in the future - for example if the contractor for some reasons doesn't want to do timesheets. at the moment, the app will force the days to be recorded by timesheets hence we remove it for now.  I think it is best to remove the code rather than comment it out but perhaps it might be an idea to make this change a separate commit so it can be looked at if ever it is needed again - though it is probably a very small change in any case.. so completely up to you if you want to separate commit or the same commit.).

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28490558-26f5b5d0-6edd-11e7-95da-fd64c1858672.png)

**Comment by fergalddaly** [comment]
Tested and working.
Made minor changes to code.
Great to have this task done.
