### ISSUE TITLE
Timesheets - Update status logic

### ISSUE THREAD

**Issue by Keroberos** [Keroberos/sam#51]
At 1 min past midnight, make the necessary updates to the entities.

Timesheets

- find those that are in the current month.
- update the status of these if necessary (if not already at status requires_updates they will be  set to that now - unless leave has been booked in).

**Comment by fergalddaly** [comment]
Hi Vitalii, 

I have this updated now but I have one issue.
I wrote a new method updateTimesheetStatus (see below) 
which I call on the timesheets for the current month 
but I get an exception because the entries are not populated in the timesheet entity.

What is the correct is the correct way to populate these entries for a timesheet entity?

I've committed the code to the branch.. 
though it doesn't work :-1: 

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.sam.service.MonthlyTimesheetService.calculateStatus(MonthlyTimesheetService.java:214)


```

```
    @Transactional
    public MonthlyTimesheetDTO updateTimesheetStatus(MonthlyTimesheetDTO monthlyTimesheetDTO) {
        MonthlyTimesheet timesheet = monthlyTimesheetMapper.toEntity(monthlyTimesheetDTO);
        MonthlyTimesheet updatedTimesheet = updateTimesheetStatus(timesheet);
        return monthlyTimesheetMapper.toDto(updatedTimesheet);
    }

```

**Comment by fergalddaly** [comment]
Branch pushed - features/SAM-51
@Keroberos - not sure how to reference a branch/commit here.

**Comment by Keroberos** [comment]
> but I get an exception because the entries are not populated in the timesheet entity.
> 
> What is the correct way to populate these entries in the timesheet entity?

I believe timesheet entries are populated, but you lost them in convertion dto->entities
I think the best approach is to avoid that conversions until you'll need to send data to the client.
![image](https://user-images.githubusercontent.com/546027/28394076-d912310c-6cea-11e7-97aa-a41a8361a5b8.png)

**Comment by fergalddaly** [comment]
Thanks. I noticed the FETCH JOIN but wasn't too sure why you had taken that approach.
I normally "manually" join it. I'll read up on that today.

I turned off the SQL as it was hard to see the other logging messages but of course, it is perfect to see the db queries.

Thanks for that.  I didn't want to force a solution in as I knew that there was a proper way of doing it.
I'll do exactly as you say and only use DTO for returning data, outside of the service class (e.g. to the REST / resoucce classes).

**Comment by fergalddaly** [comment]
I checkout and rebuilt and tested.
Looks perfect.
Will move to done shortly.
Thanks for the help.

![image](https://user-images.githubusercontent.com/2511712/28407438-0bd92e10-6d2c-11e7-82f4-dc791d461acb.png)

**Comment by Keroberos** [comment]
no problem, you're welcome

**Comment by fergalddaly** [comment]
Can you merge to master if you are happy with the code ?

**Comment by Keroberos** [comment]
done

**Comment by fergalddaly** [comment]
cheers. closing.

Think it is a good idea to have one cronservice class rather than using @Scheduled in many classes.
We can see how it goes as the ssytem develops.

Also, it is perfectly fine to use admin for now but we can consider creating a dedicated user for this at some time in the future.
