### ISSUE TITLE
TimesheetEntry update

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#52]
It was an oversight on my part.
I should have included a day number in the timesheetentry entity. #38 

- update the timesheet entity to include a day (integer) which can have a value of 1 to a maximum of 31.
- Change the code to use this value where appropriate (instead of the id).
- remove the toDay method in the MonthlyTimesheetService

Note on Validation on the server side:
I removed the code for this on the server side.
I think we can leave this functionality out for now.
The validation rules may change in the future and perhaps we can introduce the validation then when we are certain it won't need to change again.  But for now, I think the fact that the client forces the user to do the right thing is fine.  We can test the client and make sure there is no possibility that the user can break things.

**Comment by fergalddaly** [comment]
It was an oversight on my part.
I should have included a day number in the timesheetentry entity. #38 
Can you update the timesheet entity to include a day (integer) which will go from 1 to a maximum of 31?

**Comment by Keroberos** [comment]
Ok, 

> It was an oversight on my part.
> I should have included a day number in the timesheetentry entity. #38 

I was thinking, that it's by design :) Like: index of timeentry in timeEntriesCollection is day's number in the month

**Comment by fergalddaly** [comment]
:)  You did a good job using the id instead of the days! and the sorting. It all works perfectly.
I know it's now extra work to build in the day and would have been easier to have done it at the start, so sorry about that.  I prefer to have the day number in the entry as it is very obvious then, otherwise you have to work out what the day number actually is (as I did in the toDay method).  I think it is much better to have it in the entry rather than in the id field.  In the early days of computer programming then we'd leave it out and save the space in the database but those days are gone now!

**Comment by Keroberos** [comment]
No worries, I completely agree with you!
