### ISSUE TITLE
VAT Return Updates

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#54]
- Add new status ROS_PAYMENT_MADE to VAT returns
- remove the action button (and drop down menu)
- add a new button at the very end called "record ros payment."
- this button and the 2 payment details fields are disabled until the status = totalled.
- once this button is pressed, validate that the payment details have data.
- make a rest call to the server to record the payment details and change the status to ROS_PAYMENT_MADE
- disable the button and the fields (angular will do this with the status change).
- change the title of columns Payment Date to ROS Payment Date
- change the title of columns Payment Number to ROS Payment Number

**Comment by fergalddaly** [comment]
Note: ROS  Revenue Online Service is the Irish Revenue online payment system: 
https://www.ros.ie

**Comment by Keroberos** [comment]
> this button and the 2 payment details fields are disabled until the status = totalled.
> enum VatReturnStatus{ CREATED, CALCULATED, PAID }

Is 'TOTALLED' a new status too?

**Comment by fergalddaly** [comment]
I didn't really think of  a typo.
I suppose you could update it after you submitted it.
That would be a good idea.
So perhaps you can do it multiple times.
That would be fine.





I see the statuses are:
"CREATED,CALCULATED,PAID"
I meant CALCULATED rather than totalled.
I must have been looking at invoices.

**Comment by fergalddaly** [comment]
CREATED - first created by the system but cannot be calculated as data not available (e.g. invoice missing)
CALCULATED - ready for submission
ROS_PAYMENT_MADE  - the user has used the ROS website to submit the payment
PAID - this means that the user has matched an entry in the bank account with this payment.

**Comment by Keroberos** [comment]
Ok, got it, thank you

**Comment by fergalddaly** [comment]
Recorded above at https://github.com/Keroberos/sam/wiki/VAT-Returns
I'll start using the Wiki to record some info that might be useful to read and remind myself of in the future.

**Comment by fergalddaly** [comment]
I made a few mistakes in stating the requirements.
I've made an additional commit here:
0042f5663effaaa441eed5a31d37e5e1bcd78abe
to resolve the issue.

Basically, now you can execute calculate when the vat return is created.
Once it has been calculated you can record the ros payment details.
Then when the vat return is paid, no button is shown.

Above working fine now.

Further updates will be required:
- calculate will be rejected if prerequiste data (invoices, expenses) not finalised for month.
this will be covered in a different task.

Great. Can move on from this now.
