### ISSUE TITLE
Bug on Timesheets

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#56]
When you used the quick entry button then the status doesn't get updated to complete even though the timesheet is complete.

I started with an empty month and used the quick entry for all the days.

**Comment by fergalddaly** [comment]
![image](https://user-images.githubusercontent.com/2511712/28330165-79dc7122-6be4-11e7-913c-9843bd49cde7.png)

**Comment by fergalddaly** [comment]
Note: I did seem to work one time and then not another time.

**Comment by Keroberos** [comment]
Did you test it on master branch? In feature branches bugs are expected :)

**Comment by fergalddaly** [comment]
git pull on master branch and rebuilt and that is working now.
Great.
