### ISSUE TITLE
Bank Transaction Ordering

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#59]

**Comment by fergalddaly** [comment]
Bank Transactions are not always ordered by date (when uploaded).

![image](https://user-images.githubusercontent.com/2511712/28388287-1f0f10c4-6cca-11e7-8be9-9ae4f9a2ca53.png)

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28461611-ae53040e-6e17-11e7-98fa-2a51ffc6adfb.png)

**Comment by fergalddaly** [comment]
tested by loading up accounts from Jan to July.
Working perfectly now.
