### ISSUE TITLE
Timesheet - Remove planned leave

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#60]
Intro:  There must be some way to remove planned leave for the future.  Currently there isn't a way to do this.

## Changes to support the above

Note:  This change is relevant to future days only.  There is no point resetting the current or past days to unset.

1.  For any date in the future, if the status of the day is DAY OFF, offer an option "Remove planned leave" on the day drop down (and when it is clicked it will set the day back to unset)

1.  For quick entry, where one or more days of the relevant week is in the future, and where one or more of these future days is set (to DAY OFF), offer an option "Remove planned leave".   And when the user selects this option then the future days of that week that are set to DAY OFF will be set to unset.

Note:  I did think that about removing the option DAY OFF when the day is already set to DAY OFF but it is better to leave it as it is.  This is more consistent with the other days. For example, when the day is set to FULL DAY you still have 3 options rather than just 2 options.  So better to leave the option there rather than removing it..

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28407385-41ce22ac-6d34-11e7-9269-3ae5fa168c32.png)

**Comment by fergalddaly** [comment]
Perfect. Works as expected.
