### ISSUE TITLE
Update Task Entity

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#62]
## Issue 
When working on the server side functionality of tasks, I encountered an issue.
I tried to create two tasks for the same bank statement but because of the one-to-one relationship between tasks and bank statements this was not possible.
I wanted to create a task for upload and a task for reconcilation.
Currently this is not supported.
So I simply created a task for reconciliation.

## Change
So a task can be associated with 1 bank statement.
But a bank statement can be associated with many tasks.

And likewise for the other associations - invoice, expenses, vat returns.

So instead of the one-to-one use a many-to-one relationship.
I think this will result in the removal of a database constraint on the columns in question (unique).
and allow for multiple tasks against the same entity.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28520604-7b5cbf4e-7070-11e7-8110-8988b637ce9f.png)
Two task for a single bank statement
![image](https://user-images.githubusercontent.com/546027/28520681-cf4d59b0-7070-11e7-9c20-37ec687201f1.png)

**Comment by fergalddaly** [comment]
Perfect.
