### ISSUE TITLE
Update entity Invoice

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#63]
Change days to type Double as partial days (0.5) needs to be supported.

Update invoiceservice.java when this change is made:
  Integer i = workedDays.intValue(); // *** TODO *****

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28522251-95ee357a-7077-11e7-9d3f-7f2f72e3f986.png)

**Comment by fergalddaly** [comment]
Perfect.
