### ISSUE TITLE
Invoice Generation

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#67]
Note: have a good read of all of this task before starting.
Note: If you wish to give a go at the converting to PDF now (if you don't think it will take too long) then certainly do, as I really think we need this.
Note: If the PDF is stored on the entity.  So perhaps the HTML is  generated at the GENERATED status on the client and sent to the server over REST for saving on the invoice entity. Then the user can regenerate the invoice (HTML) again. When the user wants to issue the invoice the PDF is generated and emailed and the PDF is saved to the entity and then the status changes to ISSUED. and then the PDF is viewable on the client as an issued invoice... that might be a pretty good solution and clear to the user what is going on.

## New status
Add in a new status to the entity - GENERATED.
The generated status is after TOTALLED, but before ISSUED.

see note below on persisting the generated invoice and see note at end of #72 on sending invoice doc as html on invoice entity in parameter of REST call to update status.  
To support this we need to add in a String attribute to the invoice entity -- issuedInvoice.

## UI Changes

1. Change the nav bar so that timesheets comes immediately before invoices (more logical ordering).

1. Change the invoice page to look like the timesheet page with tabs for each month.

![image](https://user-images.githubusercontent.com/2511712/28587873-7de47a9e-7170-11e7-8c92-3218a07eb5f5.png)

2. In the same way as timesheets are colour codes, colour code the months are follows:

Status is CREATED and month is current or in the future - not shown.
Status is CREATED/TOTALLED and month in the past - RED
Status is GENERATED = then very light orange
Status is ISSUED = ORANGE
Status is PAID = very light green
Status is PAID = green.

3.  When you click on a month show a list of tasks:

- Submit timesheet
- Generate invoice
- Issue invoice
- Invoice has been paid
- Vat Paid on Invoice

Each task will have either a red x or a green tick on the left of it to indicate that it is either not yet done or done.

Note: It is only possible for tasks to be completed in order. Any other scenario is a bug.  It should never occur.

**Setting the ticks.**

**Submit Timesheet**
If the days have been set on the invoice then the complete timesheet will be ticked with a green tick.
If the action is not completed then show a button after the  task (Submit Timesheet) which when pressed goes to the appropriate timesheet (same as the task in the tasks page does).

**Generate Invoice**
If the status != CREATED or !=TOTALLED then the generate invoice is ticked with a green tick.
If it status is TOTALLED then show the button "Generate Invoice".

When the user clicks on generate invoice, the invoice is generated 
and shown below the list of tasks. 
The status is updated to GENERATED.

**Issue Invoice**
If the issue date is set then the "Issue Invoice" is ticked green.

If the status is GENERATED then the button "Issue Invoice" is shown.
If pressed make a rest call to update the status to ISSUED.
If the status is ISSUED then show the button but with the ext "Reissue invoice".
If pressed make a rest call to update the status to ISSUED and update issue date too.

**Invoice Paid by Agency**
If the payment date is set then invoice paid by agency is ticked green.
(No action button here).

**Vat Paid on Invoice**
If the status = VAT_PAID then the invoice VAT Paid on invoice is ticked green.
(No action button here).

### Showing the generated invoice 

Show it below the set of tasks.

Template to use:
https://drive.google.com/open?id=1n64PjHAm96G7I0K_Z6j9agsF9kJct8TOD4o-5wEoN00

Things to note:
- Company details on top left.
- Agency details below it.
- Issue date update according to issue date of invoice
- Description generated using month of invoice
- Daily rate comes from contract
- VAT Rate from server side (can hardcode to 23% on server for now as per invoice cals)

**Persisting the invoice to DB.**
The invoice when issued should be recorded in the database and then is never changed.  
(well it could be overwritten if reissued - at some point we will record outgoing emails so we'll record all versions then).
See note on client side task #72 on saving the html invoice on the invoice entity.
I think this is a good approach to resolving this issue.
So basically the HTML would be sent to the server in a REST call and saved in the entity.
We can then convert that HTML to PDF.

## HTML vs PDF
Emailing of HTML can be problematic as the styling may not work in certain email client applications.
I think it is better to send an email and the invoice as a  PDF attachment to the email.
Converting from HTML to PDF is not so difficult but at the same time will take time to configure.
I previously used https://wkhtmltopdf.org/ and it worked very well.
I want to mention this now, so you do not invest too much time into the HTML styling or resolving that in an email.  Once something is working, then that is fine for now.  And later then we will change the HTML to a PDF attachment.

**Notes**

Note:  The rest call should always be  xxx/status to update the status and then the appropriate action is taken on the server side.  This is the proper rest approach as I understand it.  The rest method is already there.

Note:  It is only possible to have one (action) button shown at any one time.. never two buttons --- and the button show is the next action perform.  

Note:  The invoice will need to be emailed to the agency and self . see #72 .  So the HTML code will need to be sent to the server and then emailed? To conversion to PDF can be done on the server. It might be an idea save as PDF rather than HTML in the entity.  Read only then.  That might be much better.

If you have any questions let me know.  And if anything doesn't seem right or does not logical sense to you, let me know too.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28747998-be761858-74ac-11e7-8a20-cc0659ee9af5.png)

**Comment by Keroberos** [comment]
Hi! I have a question - how to get agency for invoice? For now we have only one company, but many agencies. (current implementation - get first agency)

**Comment by fergalddaly** [comment]
Hi,

In order to record time you have to have a valid contract for the time (as you are recording time against a client). This change to timesheets has to be implemented yet.
And then when the invoice is being generated we have to consider the contract and associate that to the invoice.  There can be two contracts to consider when one contract ends and a new one starts - in the middle of the month.   This change has not yet been implemented either - this is the next wave/phase of the project.

For now assume that a valid contract exists for the invoice.

So retrieve the contract and from that you can get the daily rate.
And from that you can get the client.
And from that you can get the agency.

**Comment by Keroberos** [comment]
> For now assume that a valid contract exists for the invoice.
> 
> So retrieve the contract and from that you can get the daily rate.
> And from that you can get the client.
> And from that you can get the agency.

Ok, thank you. Now it's working like described - generation is based on the first contract.

**Comment by fergalddaly** [comment]
Great.  
What should I download - Jaspersoft Studio?

**Comment by fergalddaly** [comment]
The ref on the top right hand corner is an invoice reference number.

3 Letter Abbreviation for Agency
3 Letter Abbreviation for Client
YYYY
and then sequence number.

That will need to be generated and added as a attribute of the entity.

**Comment by fergalddaly** [comment]
Consultancy Services provided by <Contractor Name> to <Client Name>.
The contractor name is currently not saved.
The registration process will need to be updated to record that.
But for now, can you add it to report.  
Where is the best place to store this ?
It is linked to the user... as this is for a single user and the user is the contractor.
Just need to record the first name and last name of the user (rather than using the username).

**Comment by fergalddaly** [comment]
That everything.
Looks great.
Think when it is converted to PDF it will look the same and perfectly presentable.
I have to go now but I'll be back "online" this evening again.

Catch you soon.

**Comment by Keroberos** [comment]
> What should I download - Jaspersoft Studio?
Yes. Report template to edit is here: \src\main\resources\reports\Invoice.jrxml

> But for now, can you add it to report.
> Where is the best place to store this ?
Ok, User entity has fields like Name and Surname

**Comment by Keroberos** [comment]
> The ref on the top right hand corner is an invoice reference number.
> 
> 3 Letter Abbreviation for Agency
> 3 Letter Abbreviation for Client
> YYYY
> and then sequence number.
> 
> That will need to be generated and added as a attribute of the entity.

Created separate work item for that #84

**Comment by Keroberos** [comment]
> The contractor name is currently not saved.
> The registration process will need to be updated to record that.

Created a separate work item for that #85

**Comment by fergalddaly** [comment]
Great job. Well done getting this requirement done! :+1:
