### ISSUE TITLE
User Details Page

### ISSUE THREAD

**Issue by Keroberos** [Keroberos/sam#7]
On the right hand side, add an item to the drop menu - User Details

**Present a page with the following details**
- username
- first name, last name,
- mobile number

**Updates**

- the username cannot be updated
- allow the other fields to be updated.

note: Mobile phone change - we should require the user to respond to an activation code.  this is work to be done in the future.  not for now.

note: mobile phone communications.  I previously used a service esendex. to send messages.  I can enable that again in the future - when the sms reminders and activation is enabled.

**Comment by Keroberos** [comment]
Added to the User preferences screen https://github.com/Keroberos/sam/commit/83cd5fb4116954899b7ccfe99fd799500b1ac82f

**Comment by fergalddaly** [comment]
perfect. yea no need to add in the username.
