### ISSUE TITLE
Bank Transaction Categorization

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#75]
## Background:
- Separate the categorization of transactions from the reconciliation of transactions
- Support for reconciliation of transactions with other entities.

## Add a new status to the Bank Transaction
- CATEGORISED  (between uploaded and reconciled)

## Client Ui Changes

**Colors**
Use the primary colour (blue) that is current used for reconciled for Categorised.
Use green for Reconciled. 
The Bank Statement is reconciled when all of the transactions are reconciled.

### Update Transactions
- Add a new button on the page with text "Update transactions"
- The button is inside the month panel as it associated with the selected month.
- Add in a footer panel, which is just like the header panel for the month, and put the button on the very right of the footer panel.

**Categorisation**
- Change the fields Debit Type and Credit Type to text fields.
- When the user clicks on the Update button the fields change to drop down menus.
- The button text (and color) changes to "Finished".
- When the user clicks on Finished then the Debit Type and Credit Type dropdowns change back to text fields.  The text of the button resets to "Update transactions".
- when all the transactions have been categorised then change the status of the statement to categorised.

**Icons**
- do not show the green tick unless updating transactions (after the user has clicked on the "update transactions" button)
- to differentiate between transactions that are categorised but not yet reconciled, introduce a new color
(that is one colour for no type set, one colour for no reconciliation id set (but type set))
- the warning icons (in 2 colours) are to be shown at all times.

**Reconciliation**
- add a column to the bank transaction table - reconciliation
- only show this column if the user has clicked on "update transactions".
- When the user clicks on "Finished" then column is no longer shown.
- if the (credit or debit) type is set on the bank transaction (but no recociliation id) show a button in the column - Reconcile
- when clicked shows a Reconciliation popup (see below)

**More Details**
- Add a new extra column - More Details.
- If the reconciliation id has been set on the transaction show an icon (maybe "glyphicon glyphicon-info-sign" is a good one as the icon is to show more details).
- When the icon is clicked show the "Transaction details popup" - see below.

note: either the reconcile button or the "more details" icon can be shown. never both.

### reconciliation popup
The reconciliation popup allows the user to reconcile a bank transaction with another entity - e.g. an invoice, vat return.
- show the transaction details on the top part of the popup
- the rest of the popup is dependent on the type of transaction that is being reconciled - see below.

**Invoice** 
- if the transaction type is INVOICE Payment then show a list of invoices as a table 
- only show invoices that have a status ISSUED.
- details to show - month, year, total (with vat total), date of issue, status. 
- order by earliest to oldest.  
(note: in many cases only 1 invoice will be shown but more could be shown if the user hasn't been keeping the accounts up to date).
- on each row, show a radio button at the start of the row which allows the row to be selected.
- only one row can be selected at any one time.
- when a row is selected make this very obvious (CSS styling - maybe adding a background..)

- disable all radio buttons on rows whose invoice total != transaction credit amount.
- disable all radio buttons that related to invoices that are for months that are => the transaction month
(e.g invoice for july will be issued on 31th of July and can never be paid in July or earlier.. so if a invoice transaction for july is being reconciled this invoice will appear as disabled.  If an invoice tranaction for aug is being reconciled then this will not be disabled if the amounts match).
- add a tooltip to the disabled radio buttons either "The invoice total of [456] does not match the transaction total of [123]." or the "This invoice is for {month} and is expected to be paid in {month+1} or subsequently."
- search from first displayed invoice to invoice.month<transaction.month  and find the first invoice that has a total = transaction credit amount.  select this row (if found).

- show two buttons at the bottom of the popup box - cancel and save.
- the save button is only enabled if a row is selected. 

- when the save button is pressed then the reconciliation id of the transaction is set to the id of the selected entity (Rest call).

- when the reconciliation id is set either directly update the invoice or fire an event.  the invoice will then change status to paid.

- the popup box disappears.

**VAT Reconciliation** 
- if the transaction type is Revenue VAT Payment then show a list of VAT Payments that 
have status CALCULATED or ROS_PAYMENT_MADE

note: ideally the only status is ROS_PAYMENT_MADE but sometimes the user simply isn't going to bother to record the ROS payment details in the system but still make the ROS payment. And then the transaction will appear in the bank account so in this case we can go straight from CALCULATED to PAID.. and skip ROS_PAYMENT_MADE status.

- details to show - start date, end date, ros payment date, net payable
(very often only one payment will be shown but more could).

- order vat payments from earliest to oldest.  
- on each row, show a radio button at the start of the row for which allows the row to be selected.
- only one row can be selected at any one time.
- when a row is selected make this very obvious (CSS styling - maybe adding a background..)

- disable all radio buttons on rows whose vat return total != transaction debit amount.
- disable all radio buttons that relate to vat returns that have an end date that are => the transaction month
(e.g vat return for jun/july can only be made on 1st of Aug at the earliest, and can never be paid in July or earlier - july is the end date of the vat return -- so if a transaction in july is being consider, ignore all vat returns with end dates of july or later).
- add a tooltip to the disabled radio buttons either "The vat return total of [456] does not match the transaction total of [123]." or the "This vat return is for period {month start} to {month end}"

- search from first displayed vat return to vat return. end date<transaction.month  and find the first vat return that has a total = transaction credit amount.  select this row (if found).

- show two buttons at the bottom of the popup box - cancel and save.
- the save button is only enabled if a row is selected. 

- when the save button is pressed then the reconciliation id is set on the transaction. 

- either fire an event on save or update the status of the vat return to PAID on save.  whichever is the best approach.  The vat return status must change to PAID either way.

- the popup box disappears.

**Other reconciliation**
- Show the text "This transaction will be reconciled to a general ledger."
- show two buttons at the bottom of the dialog box - cancel and save.
when the save button is pressed then the reconciliation id is set on the transaction.
Use reconciliation ID 9999 in this case (this will changed in the future as journals for the different types of transactions are added).
the popup box disappears.

### Transaction details popup
When this is clicked show details of the transaction and the other entity that is reconciled with it.

- show a popup
- show details of the transaction
- depending on the type of transaction show details of either an invoice or vat return or other.
- invoice - show the details of the invoice. - have a button "Go to Invoices".
- vat return - show details of the invoice -  have a button "Go to Vat Returns"
- other - show a message "This transactions has been recorded in the general ledger."
- show a button, Close - when pressed, the popup box disappears.

Note: When one of the "Go to" buttons is pressed the popup disappears and the app changes to the relevant area.

<end>

**Comment by Keroberos** [comment]
Work item progress here: https://docs.google.com/document/d/13ahOQ-cHuM-91iRYc_Q4Z8ubKtBtYXt8jcYhMFp7qvc/edit?usp=sharing

**Comment by Keroberos** [comment]
> disable all radio buttons on rows whose vat return total != transaction debit amount.
Should I use "totalVatOnSales" field for this check?

**Comment by fergalddaly** [comment]
the netPayable field 
(the total amount that a person actually has to pay... (netPayable = totalVatOnSales-totalVatOnPurchases)
and when it is paid, it will then appear on the bank account).

**Comment by fergalddaly** [comment]
Tested this tonight and it is working very well.
Great job getting that done.
Looks really well and very presentable.

I now need to work on a few new categories for debit and credit. 
Next is the vat screen, and then expenses... and then credit cards and cheques...
and that'll be most of the accountancy tasks completed...

Good night.
