### ISSUE TITLE
Contract Creation

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#81]
Enforce the following rules when contracts are created:

- contracts cannot overlap (dates)  -- so at any one time only one contract will be active.

- it is possible to have multiple contracts against the same client
(e.g. contracts often roll on -- after 6 months the contract is finished and then a new contract is started with the very same agency/client).

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28997567-380884ec-7a18-11e7-9947-d64db33b4cad.png)

**Comment by Keroberos** [comment]
Added both client side and server side checks

**Comment by fergalddaly** [comment]
test and working perfectly.
