### ISSUE TITLE
First Name and Last Name

### ISSUE THREAD

**Issue by Keroberos** [Keroberos/sam#85]
-  Add a first name and last name to the user registration popup
- save details in entity 
- add to invoice template (this is covered in #86 )

note: more changes in #7

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28974497-e73f3aec-7936-11e7-85a1-3cb4c8fb7ec3.png)
![image](https://user-images.githubusercontent.com/546027/28974591-2ce93e4e-7937-11e7-8355-f2b41f205bf2.png)

**Comment by Keroberos** [comment]
Added to the User preferences screen https://github.com/Keroberos/sam/commit/83cd5fb4116954899b7ccfe99fd799500b1ac82f

**Comment by fergalddaly** [comment]
Perfect.
