### ISSUE TITLE
Vat Return File Export

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#89]
### Generate Export file Button
when the user clients on the button "ROS Vat File" generate an XML export file as described below
(see #58 for info on the button).

### XML format
- see below for an example of the XML format
- appropriately set regNum, startdate, enddate, sales, purchs in the generate file (using the values on the VAT return of the row)
- the other totals are 0 (as shown below).
- for more information on the format see http://rospublictest.ros.ie/schemas/vat3/vat3api.pdf
- set the XML file name to vat3_<start>_<end>.xml where the start and end are of the format MMYYYY and represent the start period and end period of the vat return in question (e.g. vat3_012017_022017.xml)

### Example XML File
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<VAT3 currency="E" name="Trade Name" regnum="1234567T" startdate="01/01/2001" enddate="28/02/2001"
sales="999999999" purchs="999999999" goodsto="0" goodsfrom="0"
servicesto="0" servicesfrom="0" type="0" filefreq="0" formversion="1" language="E" />
```

### Testing File

Use the following to test the generated XML file 

https://rospublictest.ros.ie/VAT3Upload/testfile

The following should appear if the file is in the correct format:

![image](https://user-images.githubusercontent.com/2511712/28798516-a2fc2068-763c-11e7-8de2-899874bd6638.png)

**Comment by fergalddaly** [comment]
[vatReturn.txt](https://github.com/Keroberos/sam/files/1188839/vatReturn.txt)

**Comment by fergalddaly** [comment]
![image](https://user-images.githubusercontent.com/2511712/29194661-9c1facf4-7e22-11e7-9109-62ccc4fa90b1.png)

**Comment by fergalddaly** [comment]
Tested using ROS VAT file tester.
Working perfectly.
Task completed.

**Comment by Keroberos** [comment]
Hi! Just want to confirm: I'm using Company name and Company reg vat number to generate xml, Is it correct?

**Comment by fergalddaly** [comment]
That's perfect. That's exactly what is required.

I tested it using https://rospublictest.ros.ie/VAT3Upload/testfile and it accepted the format.
But I suppose it is probably not looking at the actual company name.
It probably is validating the VAT number.

So perfect.
