### ISSUE TITLE
Date Refactor

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#91]
### Date Tidy

- remove 2017 hard coding in domain objects
- fix any issues arising out of date changes.

**Comment by fergalddaly** [comment]
@Keroberos - could you help with a few items on this task.  I prefer to get this right on the branch before committing and merging to the main branch.

######################################################
can you update table of tasks to list them in order of due date.
I think the file is ./display-monthly-tasks.component.html
(note: i removed the setting of the order as I think this is unnecessary).

![image](https://user-images.githubusercontent.com/2511712/28958391-1ef881b2-78ee-11e7-936b-27aeac9531f6.png)

#######################################################

The quick entry button does not work properly for the very first week of the Dec 2016 timesheet.
It does make the rest call to the server and the data is updated.  It is just not shown properly on the client.

#########################################################

**Comment by Keroberos** [comment]
Hi Fergal,
I've faced an issue with year 2016 - we have a lot of constraints on DB side with min_value=2017 for the year and updates on this rows will fail.

**Comment by Keroberos** [comment]
>The quick entry button does not work properly for the very first week of the Dec 2016 timesheet.
Fixed

> The invoice thinks that the timesheet has not been submitted even though it has been.

It happens because of missing contract. I'll add contract generation for this period.

**Comment by fergalddaly** [comment]
On the branch, updated the .json file but then manually updated the domain objects - changing 2017 to 2016.  That should resolve this ?

**Comment by Keroberos** [comment]
Let me look into that, I'm almost finish this fix

**Comment by Keroberos** [comment]
> result = `This invoice is for ${invoice.month}/${invoice.year} and is expected to be paid in month ${invoice.month+1}.`;

What if invoice.month==12? :)

**Comment by fergalddaly** [comment]
I wasn't too sure how to write that in typescript!!!
Perhaps you can change it to be the name of the month+1 ?  (e.g. Dec+1=Jan, Feb+1 = March and so on).
I  need to put some time aside to learn typescript properly!

**Comment by Keroberos** [comment]
Sure, no problem
