### ISSUE TITLE
Vat Returns Client Updates - Part 2

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#92]
# The VAT Tab

### Top part of tab content

Show the following details

- VAT Period --- Start and End

- Vat Due Date 

if the vat status == CREATED or CALCULATED and the due date is in the past, then show the following text in red "This VAT Return is overdue."

- ROS Payment Details (Date and Payment Number) - show if status is CALCULATED (with blank values) or if status is ROS_PAYMENT_MADE or if PAID.  

- Status (Generated text - not the status of the actual vat return)

**only one of the following options (in order)**

- get the task SUBMIT_VAT_RETURN for this vat return.  If the status of this is has pre-requiste tasks then "This VAT return cannot be generated as there are outstanding tasks".

- otherwise, if the status is CREATED then present the following text "This VAT return can now be generated" and present a button "Generate" which will generate the vat return (this is the same as the current Calculate button).  In this case the middle section (see below) will not be displayed.

- otherwise, if the status is CALCULATED then present the following text "This VAT return has been generated. A payment must be made on ROS and details recorded here.".  
present the button **Generate ROS Export File**.
present the button **Record ROS Payment details**.
the middle panel is shown for this and other statuses.

- if the status is ROS_PAYMENT_MADE then present the text "The payment has been made on ROS."
- if the status is PAID, show the text "This VAT return has been paid to Revenue from company account." 

### Middle Panel of Page

Show the following sections

- Vat On Sales
- Vat On Purchases
- Net Payable 

**Vat on Sales Section**
- List the invoices that are associated with this vat return
- Show invoice details  --- month, year, days, amount without vat, rate of vat, vat amount, total
- Show vat amount in bold
- After the list (table) show a vat total --- display the vat on sales total value .

(note: this will be the same as the sum of the individual vat amounts).

**Vat On Purchases**

- this is not yet supported properly so best to leave the list of items empty.

- At the end show a vat total - display the vat on purchases total value

**Net Payable**

- show the net payable amount.

### New buttons

**Generate ROS Export File**
- add a button to the Vat Return table, "Generate ROS Export File" which will allows the Vat Return to be downloaded (and then uploaded to ROS).
- when the button is clicked, generate an XML file which can be saved by the user
- see #89 for details

**Save Ros Payment Details Popup Dialog**
- add a new button  to the Vat Return table, "Record ROS Payment details"
- when this button is clicked show a popup dialog which allows the user to enter the ros payment date and the ros payment number --  buttons cancel and save.
- when save is pressed make the call that is done for the "Save Ros Payment" button on the current ui

**Comment by Keroberos** [comment]
> if the vat status == CREATED or TOTALLED 

I can't see TOTALLED  status in the vat return statuses. Do I need to create it?

**Comment by fergalddaly** [comment]
sorry, I meant to CALCULATED when I wrote TOTALLED.

**Comment by Keroberos** [comment]
![92](https://user-images.githubusercontent.com/546027/29166143-86d29a76-7dc5-11e7-86b9-75213c820655.png)

**Comment by fergalddaly** [comment]
working perfectly.
vat returns working well and nice to have the XML export done too!
:+1:
