### ISSUE TITLE
User Mobile Updates

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#93]
### entity change

- update user entity to include mobile number.

### user registration change

- add user mobile to user registration popup.

### preferences page

- change "User preferences" to "User Details" on sub panel

- move mobile phone number from user preferences to User details section 

### invoice change

- update invoice creation to include user's mobile

**Comment by Keroberos** [comment]
> update invoice creation to include user's mobile

In the invoice template I can see only company mobile phone... Should I put user's mobile phone in that field?

**Comment by fergalddaly** [comment]
Yes, that will be fine for now as in almost all cases they will be the same.

At the same time, the company details could be different from the user's details.
I have made a note in #82 and in the future, we can extend the company to include contact details and put that in the invoice rather than the personal number of the contractor.. 

(note: the app is for a company with a single contractor/employee so for now we can use the personal number).

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28995828-aeee2870-79f3-11e7-8df2-f3d366b9a0cd.png)
![image](https://user-images.githubusercontent.com/546027/28995832-c6af3a26-79f3-11e7-9f06-02dd4bb66f4f.png)
![image](https://user-images.githubusercontent.com/546027/28995820-a436653c-79f3-11e7-98ed-0c23b5913901.png)

**Comment by fergalddaly** [comment]
tested.
working perfectly.
