### ISSUE TITLE
Reconciliation Fix

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#94]
Reverted changes that were not working in 
e3e3474c9dfb40f67705293b0a72d27910813427

@Keroberos - can you have a look and change again to what you were hoping to achieve.

I used the following file to test:

- [banktrans.txt](https://github.com/Keroberos/sam/files/1202212/banktrans.txt)
- this file has a few months of transactions
- using this file all you have to do is submit timesheets and issue invoices and then reconcile
- then you can reconcile the vat amount with the vat return too.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28994339-d47072ec-79cb-11e7-8a80-00a033b71d4c.png)
