### ISSUE TITLE
Sending old Invoices not required.

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#96]
## Background
In some circumstance you must input historical data for months that are in the past.
For example, when starting to use the system for the very first time, you will need to fill in historical data and bring the system up to date.

Note:  See the very last change at the end of this task.  The issue button as it currently is can be reused for that part.  The only change is that it will not change the status now.

## Invoices
**Objectives**
- In these circumstances, you do not need to issue the invoice to the agency or self as this will have already been done (externally from the system) in the past.   
- Allow generated invoices to be marked as issued without actually emailing the invoice
- Allow the issued date to be entered manually but offer a sensible default that will be sufficient in most cases.
- Allow the invoice to be emailed at any time

**Change to Invoices**
- Only show the issue button when the issue date is not set (I think this is the current case)
- Do not show the reissue button. Remove this.

Note:  So the invoice can only be issued once.  The invoice can sent by email at any time.

- When the issue button is pressed show a popup dialog box.

**Top Section**
Offer two radio button options:
- Issue this invoice now.
- This invoice has already been issued

**Issue Now Option**
- When the "issue now" option is selected then display (or enable) the following options (as already currently offered):

![image](https://user-images.githubusercontent.com/2511712/29087400-b5696f4e-7c6d-11e7-9af9-d0b56786591c.png)

- update to display the actual email addresses of each recipient  (e.g. display (fergalddaly@gmail.com) after self).
- the button should read "Send" when this option is chosen.

**Already Issued option**
- When this option is selected show (or enable) an input field, "Date of Issue".
- The default value of this input field is the last day of the month of the invoice.
- The user can update the Date of Issue default value or can simply leave it as it is.
- Show buttons Cancel and Save.
- When Save is pressed then issue date is updated on the invoice to the one specified and the status of the invoice is changed to issued.  The popup will disappear.  an email will not be sent in this case.

Note:  If the cancel button is selected then the invoice should not be changed to issued and the issue date of the invoice should not be set (I think this might be happening now).

**Reissue**
- remove the option to reissue the invoice from the "task section" of the invoice page.

**Emailing at any time.**
- Allow any generated invoice to be emailed to agency or self at any time.
- Create a bottom banner just like you have done for bank transactions and put the send invoice button on the bottom right of that... just the same as "Update Transactions"
- This button should not be shown if there is no generated invoice to send.
- Button text "Email invoice"
- Show the very same popup as (email to agency, email to self options with cancel and send buttons) as is current shown for issuing an invoice
![image](https://user-images.githubusercontent.com/2511712/29087400-b5696f4e-7c6d-11e7-9af9-d0b56786591c.png)

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/29239684-20a80fb6-7f54-11e7-9b7b-c86214df72a5.png)

**Comment by fergalddaly** [comment]
### Modification to style and text

**Original Version**

![image](https://user-images.githubusercontent.com/2511712/29240445-6f570bea-7f5d-11e7-804a-aaf4fc82a821.png)

**New Version:**

![image](https://user-images.githubusercontent.com/2511712/29240506-d6fe8b6e-7f5e-11e7-894c-bdc66e681c2c.png)

**Comment by fergalddaly** [comment]
Tested and working perfectly.

**Comment by fergalddaly** [comment]
Tested and working perfectly.
