### ISSUE TITLE
Invoice Reconciliation

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#97]
### Reconciliation Popup

**Invoice changes**
- (change of order) : show list of invoices in order of date from oldest to the newest (reverse of current order)
- from the invoice list remove the date of issue and the status
- use css style "opacity: 0.5;"  for rows that are disabled.

**Manually creating invoice**
Background:  In the very first month of the system, a transaction will most likely exist for an invoice payment but the invoice will not be on the system (as the invoice will be for the previous month).  So allow the invoice to be manually generated from the transaction.

-  if in the first month (of the application) and invoice payment is not reconciled, in the reconciliation popup show a button "Manually create invoice".
- when the button is selected show a popup - Manual Invoice Creation.
- show the following fields,

- Month and Year (defaulted to previous month. can only be set to date within a contract. when set, set agency and client - see below)
- Date of Issue (set to last day of selected month/year - ready only).
- Days (calculated and set to read only -- gross amount/rate)
- Rate (set to value from contract and read only)
- Gross Amount (set to value total/1.23 and read only)
- VAT Rate (set to value 23% and read only)
- VAT Amount (gross*.23)
- Total Amount (set to value of transaction and read only)
- Agency  (from contract)
- Client  (from contract).

Note:  The above will be fine as the dummy data creates a contract from start of 2016 to the end of 2017.  When the user registers on the system initially then the contract needs to start before the start date of the system (1 month back) so that the above will work.  I have added this as a note in #82

**Buttons**

- show a cancel and a create button
- when the create button is pressed the invoice is created (REST call) (status is issued)
- after it is created, the popup disappears and the user is returned to the reconciliation popup.  Now the invoice that has just been created appears on the list of invoices - and it can be reconciled with the bank transaction; it is enabled for selection.

**Comment by Keroberos** [comment]
> Month and Year (defaulted to previous month. can only be set to date within a contract. when set, set agency and client - see below)

Do we need to set some restrictions on that fields? Like MAX_VALUE = previous month?

**Comment by fergalddaly** [comment]
I think the approach that you are after taking is perfect.
The contract needs to be found.
I'll be able to test later today.  Will let you know then.

**Comment by fergalddaly** [comment]
That's working perfectly.
Great to have this done.
