### ISSUE TITLE
Reconciliation of Vat Payments

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#98]
### Vat changes
- show list of vat returns from oldest to the newest (reverse of current order)
- use css style "opacity: 0.5;"  for rows that are disabled.

### Manually Create VAT return

**Reasoning**
When a bank transaction is set to VAT Payment  then it could be the case that the vat payment is related to a period that is outside of the app start date.

**Changes**
- Show a button on the VAT return reconciliation popup -  "VAT Return period before MM/YYYY"  (where MM/YYYY is the start month of the system).
- show the button at the end of the list of vat returns 
- When the button is clicked, show a list of VAT return periods for the previous 6 months (e.g. Nov-Dec, Sept-Oct and July-Aug that do not already exist with status of PAID).  show most recent first (e.g. Nov-Dec first).  Show the start period, end period only.
- Allow the user to select any one of the options (vat return periods).
- When one of these is selected and the save button is pressed then create a vat return entity setting the 
Net Payable to the transaction total and then associate the bank transaction with the vat return.  set the status of the vat payment to PAID.

**Comment by Keroberos** [comment]
Hi! Could you please answer a few questions:
1) We're setting invoice id\vat return id in reconciliation_id of bank transaction . But we also have BANK_TRANSACTION_ID  in Invoice and VatReturn, do we need to set it too?
2) How can I get the start month of the system? Is it from user's settings?

**Comment by fergalddaly** [comment]
I am not at my computer but i will answer.

1. Yes.  I created that so that we can easily go from an invoice or vat
return back to the bank transaction.

2.  That is inputted at the very start.  I think it might be recorded in
the company.

On 18 Aug 2017 19:45, "Kero" <notifications@github.com> wrote:

Hi! Could you please answer a few questions:

   1. We're setting invoice id\vat return id in reconciliation_id of bank
   transaction . But we also have BANK_TRANSACTION_ID in Invoice and
   VatReturn, do we need to set it too?
   2. How can I get the start month of the system? Is it from user's
   settings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Keroberos/sam/issues/98#issuecomment-323431821>, or mute
the thread

**Comment by fergalddaly** [comment]
Checked out the branch and compiled it and tested the new functionality and that looks perfect.
The user can now specify that the payment out is for a VAT return and the user can still reconcile it even though the vat return was for a period that wasn't covered by the start of the system. 
Great.

**Comment by fergalddaly** [comment]
When you're happy that the code is complete, can you merge and close this task then.
Thanks.
Getting closer to the end of phase 1 :+1:
